import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Quick Start sidebar
  quickStartSidebar: [{type: 'autogenerated', dirName: 'quick-start'}],
  
  // Standards & Regulations sidebar
  standardsSidebar: [{type: 'autogenerated', dirName: 'standards'}],
  
  // Implementation Guides sidebar (both build-phase and operate-phase)
  implementationSidebar: [{type: 'autogenerated', dirName: 'implementation'}],
  
  // A single, combined sidebar for all tools, templates, and resources
  resourcesSidebar: [{type: 'autogenerated', dirName: 'resources'}],

  // Tools sidebar
  toolsSidebar: [{type: 'autogenerated', dirName: 'tools'}],
};

export default sidebars;
